### ISSUE TITLE
Generate an error page when compilation fails

### ISSUE THREAD

**Issue by olivierchatry** [sveltejs/rollup-plugin-svelte#105] opened 2020-05-12 08:01 UTC
Hello !

Was wondering if it is possible to generate an error page when compilation fails. Not sure if this would be the right plugin where to add this code, but it would be very nice.
In our projects, we are using live reload, but we have to look a the console to be sure that svelte is actually able to compile. It's a bit cumbersome, and it would be nice if, when compilation fails, a placeholder page is generated with information about the error.

**Comment by Conduitry** [comment] 2020-05-12 13:03
Duplicate of https://github.com/sveltejs/template/issues/79

**Closed by Conduitry** 2020-05-12 13:03 UTC
