### ISSUE TITLE
[Bug] Unterminated comment

### ISSUE THREAD

**Issue by Afsoon** [sveltejs/rollup-plugin-svelte#133] opened 2020-09-28 07:11 UTC
Hello everyone, today while I was written some comments, I discover that the svelte plugin can't parse a comment with a `script tag` inside of the comment. The error is `Unterminated comment` even if you the comments closed.

## Steps to reproduce
The following codesanbox hast the minimal code https://codesandbox.io/s/intelligent-liskov-yye07?file=/Button.svelte

## Workaround
Remove the tags from the script tag inside of the comment

## Expected
The rollup plugin ignore the script tag inside the comment

## Versions
Svelte: 3.28
Rollup Svelte Plugin: 5.0.3

I don't know if it's intentional this error or no, I couldn't find any place that say isn't allowed to write that.

**Comment by TehShrike** [comment] 2020-09-28 13:29
That's not a Svelte or Rollup issue, that's how parsing script tags works everywhere.

Try opening this html file in your browser to see the same behavior:

```html
<html>
	<script>
		/*
			</script>
		*/
	</script>
</html>
```

**Comment by Conduitry** [comment] 2020-09-28 13:53
This is a duplicate of https://github.com/sveltejs/svelte/issues/3039 / https://github.com/sveltejs/svelte/issues/3840 / https://github.com/sveltejs/svelte/issues/4406 / https://github.com/sveltejs/svelte/issues/4996 / https://github.com/sveltejs/svelte/issues/5024 / https://github.com/sveltejs/svelte-repl/issues/126 / maybe others, and is not a bug. This is how parsing inline script tags works in HTML.

**Closed by Conduitry** 2020-09-28 13:53 UTC
