### ISSUE TITLE
hot reloading doesn't work on styles "text/sass" with @import 

### ISSUE THREAD

**Issue by bugleev** [sveltejs/rollup-plugin-svelte#67] opened 2019-09-26 20:43 UTC
I have a component with style preprocessor like this:
``` javascript
<style type="text/sass">
@import "./test.sass"
</style>
 ```
when contents of test.sass are changed in dev mode, styles are not updated in the browser.
Although when i'm not using @import:
``` javascript
<style type="text/sass">
.someClass
  color: red
</style>
 ```
hot reloading works ok after styles update, is this a bug or?

**Comment by Conduitry** [comment] 2019-09-26 21:37
This is going to depend on what preprocessor you're using for Sass. It's the preprocessor's responsibility to report additional dependencies that should trigger rebuilds.

**Comment by perfaram** [comment] 2020-08-12 22:30
Except, that this plugin actually reports the dependencies : https://github.com/ls-age/svelte-preprocess-sass/blob/06026f0b4e56b2b96feccb0da251a82673969f06/src/index.js#L27
The issue is then likely not with said plugin (having verified that the `dependencies` array actually contains an accurate list of files to watch).

**Comment by lukeed** [comment] 2020-10-20 04:33
Closing – linked `svelte-preprocess` issue could not reproduce // OP found solution.

**Closed by lukeed** 2020-10-20 04:33 UTC
Labels: question
